import { useState } from 'react'
import { ArrowRight, BookOpen, Copy, FileDown, FileText, Layers3, MessageCircle, RotateCcw } from 'lucide-react'
import { askSources, generateFlashcards, generateNotes, generateQuiz } from '../lib/ai'
import type { AppData, ChatThread, ClassRecord, Flashcard, Note, Quiz, SourceMaterial } from '../models'

type Tab = 'overview' | 'materials' | 'lessons' | 'notes' | 'flashcards' | 'quizzes' | 'ask'
type Props = { data: AppData; selectedId: string; onSelect: (id: string) => void; onChange: (fn: (data: AppData) => AppData) => void; onAddClass: (name: string) => void; onOpenCourse: (id: string) => void; onGenerateLessons: () => void }
const id = () => crypto.randomUUID()

async function hasAI() {
  if (!window.speedyAI) return false
  const [state, provider] = await Promise.all([window.speedyAI.localAI.getState(), window.speedyAI.provider.get()])
  return ['ready', 'installed'].includes(state.status) || provider.type === 'custom'
}

function scopedSources(data: AppData, classId: string) {
  const direct = data.sources.filter((source) => source.classId === classId)
  return direct.length ? direct : data.sources
}

export function ClassesView(props: Props) {
  const { data, selectedId, onSelect, onChange, onAddClass, onOpenCourse, onGenerateLessons } = props
  const [tab, setTab] = useState<Tab>('overview')
  const [newClass, setNewClass] = useState('')
  const selected = data.classes.find((item) => item.id === selectedId) || data.classes[0]
  if (!selected) return <div className="page simple-empty"><h1>No classes yet</h1><p>Add a class to organize materials and generated study content.</p><div className="inline-entry"><input value={newClass} onChange={(event) => setNewClass(event.target.value)} placeholder="Class name" /><button className="button" onClick={() => { if (newClass.trim()) onAddClass(newClass.trim()); setNewClass('') }}>Add class</button></div></div>
  const sources = scopedSources(data, selected.id)
  const courses = data.courses.filter((course) => !course.classId || course.classId === selected.id)
  return <div className="page classes-page"><header className="page-heading compact"><div><p className="kicker">CLASSES</p><h1>{selected.name}</h1></div><select aria-label="Choose class" value={selected.id} onChange={(event) => { onSelect(event.target.value); setTab('overview') }}>{data.classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></header>
    <nav className="class-tabs">{(['overview', 'materials', 'lessons', 'notes', 'flashcards', 'quizzes', 'ask'] as Tab[]).map((item) => <button key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</nav>
    {tab === 'overview' && <div className="plain-list"><button onClick={() => setTab('materials')}><FileText /><span><strong>{sources.length} materials</strong><small>Source files for this class</small></span><ArrowRight /></button><button onClick={() => setTab('lessons')}><BookOpen /><span><strong>{courses.length} courses</strong><small>{courses.reduce((sum, course) => sum + course.lessons.length, 0)} generated lessons</small></span><ArrowRight /></button><button onClick={() => setTab('flashcards')}><Layers3 /><span><strong>{data.flashcards.filter((card) => card.classId === selected.id).length} flashcards</strong><small>Review cards due today</small></span><ArrowRight /></button></div>}
    {tab === 'materials' && <SimpleRows rows={sources.map((source) => ({ title: source.name, meta: `${source.type.toUpperCase()} · ${source.chunks.length} sections` }))} empty="No materials assigned yet." />}
    {tab === 'lessons' && <div><div className="subpage-action"><p>Short, ordered courses generated from your class material.</p><button className="button" onClick={onGenerateLessons}>Generate lessons</button></div><div className="plain-list">{courses.map((course) => <button key={course.id} onClick={() => onOpenCourse(course.id)}><BookOpen /><span><strong>{course.title}</strong><small>{course.lessons.length} lessons · {course.estimatedMinutes} min</small></span><ArrowRight /></button>)}</div></div>}
    {tab === 'notes' && <NotesPanel data={data} classItem={selected} sources={sources} onChange={onChange} />}
    {tab === 'flashcards' && <FlashcardsPanel data={data} classItem={selected} sources={sources} onChange={onChange} />}
    {tab === 'quizzes' && <QuizzesPanel data={data} classItem={selected} sources={sources} onChange={onChange} />}
    {tab === 'ask' && <AskPanel data={data} classItem={selected} sources={sources} onChange={onChange} />}
  </div>
}

function SimpleRows({ rows, empty }: { rows: { title: string; meta: string }[]; empty: string }) { return rows.length ? <div className="simple-rows">{rows.map((row) => <div key={row.title}><strong>{row.title}</strong><small>{row.meta}</small></div>)}</div> : <p className="muted-empty">{empty}</p> }

function NotesPanel({ data, classItem, sources, onChange }: { data: AppData; classItem: ClassRecord; sources: SourceMaterial[]; onChange: Props['onChange'] }) {
  const notes = data.notes.filter((note) => note.classId === classItem.id)
  const [active, setActive] = useState(notes[0]?.id || '')
  const [busy, setBusy] = useState(false)
  const note = notes.find((item) => item.id === active)
  async function create() { setBusy(true); try { const markdown = await hasAI() ? await generateNotes(sources) : `# ${classItem.name} notes\n\n${sources.flatMap((source) => source.chunks).slice(0, 6).map((chunk) => `## ${chunk.heading || 'Key concept'}\n\n${chunk.content}`).join('\n\n')}`; const now = new Date().toISOString(); const next: Note = { id: id(), classId: classItem.id, sourceIds: sources.map((source) => source.id), title: `${classItem.name} study notes`, markdown, createdAt: now, updatedAt: now }; onChange((current) => ({ ...current, notes: [next, ...current.notes] })); setActive(next.id) } finally { setBusy(false) } }
  function download(item: Note) { const blob = new Blob([item.markdown], { type: 'text/markdown' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${item.title}.md`; link.click(); URL.revokeObjectURL(link.href) }
  return <div className="feature-panel"><div className="subpage-action"><p>Editable notes grounded in class material.</p><button className="button" disabled={!sources.length || busy} onClick={create}>{busy ? 'Generating…' : 'Generate notes'}</button></div>{notes.length > 0 && <select value={active} onChange={(event) => setActive(event.target.value)}>{notes.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select>}{note ? <div className="note-editor"><input value={note.title} onChange={(event) => onChange((current) => ({ ...current, notes: current.notes.map((item) => item.id === note.id ? { ...item, title: event.target.value, updatedAt: new Date().toISOString() } : item) }))} /><textarea value={note.markdown} onChange={(event) => onChange((current) => ({ ...current, notes: current.notes.map((item) => item.id === note.id ? { ...item, markdown: event.target.value, updatedAt: new Date().toISOString() } : item) }))} /><div><button className="button secondary" onClick={() => navigator.clipboard.writeText(note.markdown)}><Copy size={15} />Copy</button><button className="button secondary" onClick={() => download(note)}><FileDown size={15} />Export Markdown</button><button className="button secondary" disabled={busy} onClick={create}><RotateCcw size={15} />Regenerate</button></div></div> : <p className="muted-empty">Generate your first set of notes from this class.</p>}</div>
}

function FlashcardsPanel({ data, classItem, sources, onChange }: { data: AppData; classItem: ClassRecord; sources: SourceMaterial[]; onChange: Props['onChange'] }) {
  const cards = data.flashcards.filter((card) => card.classId === classItem.id)
  const [index, setIndex] = useState(0); const [flipped, setFlipped] = useState(false); const [busy, setBusy] = useState(false)
  const card = cards[index % Math.max(cards.length, 1)]
  async function create() { setBusy(true); try { const generated = await hasAI() ? await generateFlashcards(sources) : sources.flatMap((source) => source.chunks).slice(0, 8).map((chunk) => ({ front: chunk.heading || 'What is the key idea?', back: chunk.content.split(/[.!?]/)[0], sourceChunkIds: [chunk.id] })); const now = new Date().toISOString(); const next: Flashcard[] = generated.map((item) => ({ id: id(), classId: classItem.id, sourceIds: sources.map((source) => source.id), concept: item.front, front: item.front, back: item.back, explanation: 'Generated from your imported material.', dueAt: now, intervalDays: 0, ease: 2.5, reviewHistory: [] })); onChange((current) => ({ ...current, flashcards: [...current.flashcards, ...next] })) } finally { setBusy(false) } }
  function rate(rating: 'again' | 'hard' | 'good' | 'easy') { if (!card) return; const days = rating === 'again' ? 0 : rating === 'hard' ? 1 : rating === 'good' ? Math.max(2, Math.round(card.intervalDays * card.ease) || 3) : Math.max(4, Math.round(card.intervalDays * (card.ease + .35)) || 6); const dueAt = new Date(Date.now() + days * 86400000).toISOString(); onChange((current) => ({ ...current, flashcards: current.flashcards.map((item) => item.id === card.id ? { ...item, dueAt, intervalDays: days, ease: Math.max(1.3, item.ease + (rating === 'again' ? -.2 : rating === 'easy' ? .15 : 0)), reviewHistory: [...item.reviewHistory, { rating, reviewedAt: new Date().toISOString(), dueAt }] } : item) })); setFlipped(false); setIndex(index + 1) }
  return <div className="feature-panel"><div className="subpage-action"><p>{cards.length} cards · {cards.filter((item) => new Date(item.dueAt) <= new Date()).length} due</p><button className="button" disabled={!sources.length || busy} onClick={create}>{busy ? 'Generating…' : 'Generate flashcards'}</button></div>{card ? <><button className="flashcard" onClick={() => setFlipped(!flipped)}><small>{flipped ? 'ANSWER' : 'QUESTION'}</small><strong>{flipped ? card.back : card.front}</strong><span>Click to flip</span></button>{flipped && <div className="rating-row">{(['again', 'hard', 'good', 'easy'] as const).map((rating) => <button key={rating} onClick={() => rate(rating)}>{rating[0].toUpperCase() + rating.slice(1)}</button>)}</div>}</> : <p className="muted-empty">Generate flashcards to start spaced review.</p>}</div>
}

function QuizzesPanel({ data, classItem, sources, onChange }: { data: AppData; classItem: ClassRecord; sources: SourceMaterial[]; onChange: Props['onChange'] }) {
  const quizzes = data.quizzes.filter((quiz) => quiz.classId === classItem.id); const quiz = quizzes[0]
  const [question, setQuestion] = useState(0); const [answers, setAnswers] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false)
  async function create() { setBusy(true); try { const raw = await hasAI() ? await generateQuiz(sources) : sources.flatMap((source) => source.chunks).slice(0, 5).map((chunk) => ({ question: `Which statement matches ${chunk.heading || 'this concept'}?`, options: [chunk.content.split(/[.!?]/)[0], 'It is not discussed in the source', 'It is the opposite of the source', 'None of these'], correctAnswer: chunk.content.split(/[.!?]/)[0], explanation: 'This answer is stated in the imported material.', sourceChunkIds: [chunk.id] })); const next: Quiz = { id: id(), classId: classItem.id, sourceIds: sources.map((source) => source.id), title: `${classItem.name} practice quiz`, questions: raw.map((item) => ({ ...item, id: id(), kind: 'multiple-choice', concept: item.question })), attempts: [], createdAt: new Date().toISOString() }; onChange((current) => ({ ...current, quizzes: [next, ...current.quizzes] })); setQuestion(0); setAnswers({}) } finally { setBusy(false) } }
  const item = quiz?.questions[question]; const answer = item && answers[item.id]
  function finish() { if (!quiz) return; const correct = quiz.questions.filter((item) => answers[item.id] === item.correctAnswer).length; onChange((current) => ({ ...current, quizzes: current.quizzes.map((item) => item.id === quiz.id ? { ...item, attempts: [...item.attempts, { answers, correct, total: item.questions.length, completedAt: new Date().toISOString() }] } : item) })) }
  return <div className="feature-panel"><div className="subpage-action"><p>{quiz ? `${quiz.questions.length} questions · ${quiz.attempts.length} attempts` : 'Practice with source-grounded questions.'}</p><button className="button" disabled={!sources.length || busy} onClick={create}>{busy ? 'Generating…' : quiz ? 'New quiz' : 'Generate quiz'}</button></div>{item ? <div className="quiz-card"><small>QUESTION {question + 1} OF {quiz.questions.length}</small><h2>{item.question}</h2><div className="answers compact-answers">{item.options?.map((option) => <button key={option} disabled={Boolean(answer)} className={answer ? option === item.correctAnswer ? 'correct' : option === answer ? 'incorrect' : '' : ''} onClick={() => setAnswers({ ...answers, [item.id]: option })}>{option}</button>)}</div>{answer && <div className="feedback"><strong>{answer === item.correctAnswer ? 'Correct' : 'Not quite'}</strong><p>{item.explanation}</p><button className="button" onClick={() => { if (question + 1 === quiz.questions.length) finish(); else setQuestion(question + 1) }}>{question + 1 === quiz.questions.length ? 'Finish quiz' : 'Next question'}</button></div>}</div> : <p className="muted-empty">Generate a quiz from this class’s material.</p>}</div>
}

function AskPanel({ data, classItem, sources, onChange }: { data: AppData; classItem: ClassRecord; sources: SourceMaterial[]; onChange: Props['onChange'] }) {
  const existing = data.chats.find((chat) => chat.classId === classItem.id)
  const [question, setQuestion] = useState(''); const [busy, setBusy] = useState(false)
  const messages = existing?.messages || []
  async function send() { const text = question.trim(); if (!text) return; setQuestion(''); setBusy(true); const now = new Date().toISOString(); const thread: ChatThread = existing || { id: id(), classId: classItem.id, sourceIds: sources.map((source) => source.id), title: classItem.name, messages: [], createdAt: now, updatedAt: now }; const user = { id: id(), role: 'user' as const, content: text, createdAt: now }; onChange((current) => ({ ...current, chats: existing ? current.chats.map((chat) => chat.id === thread.id ? { ...chat, messages: [...chat.messages, user], updatedAt: now } : chat) : [{ ...thread, messages: [user] }, ...current.chats] })); try { const content = await hasAI() ? await askSources(text, sources) : 'Set up Local AI in Settings → Models to ask grounded questions about your material.'; const assistant = { id: id(), role: 'assistant' as const, content, sourceChunkIds: sources.flatMap((source) => source.chunks).slice(0, 3).map((chunk) => chunk.id), createdAt: new Date().toISOString() }; onChange((current) => ({ ...current, chats: current.chats.map((chat) => chat.id === thread.id ? { ...chat, messages: [...chat.messages, assistant], updatedAt: assistant.createdAt } : chat) })) } finally { setBusy(false) } }
  return <div className="ask-panel"><div className="chat-log">{messages.length ? messages.map((message) => <div key={message.id} className={`chat-message ${message.role}`}><strong>{message.role === 'user' ? 'You' : 'SpeedyAI'}</strong><p>{message.content}</p>{message.sourceChunkIds?.length ? <small>Grounded in {message.sourceChunkIds.length} source sections</small> : null}</div>) : <div className="muted-empty"><MessageCircle /><p>Ask a question about this class. Answers stay grounded in imported material.</p></div>}</div><div className="ask-entry"><input value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') send() }} placeholder="Ask about your material…" /><button className="button" disabled={busy || !question.trim()} onClick={send}>{busy ? 'Thinking…' : 'Ask'}</button></div></div>
}
